### PR TITLE
Add vectors generated by specs actors v6 tests

### PR DESCRIPTION
**Pull request by ZenGround0**

### CODE REVIEW

**Comment by raulk** [comment]
@ZenGround0 Apparently the GitHub UI grinds to a halt with this PR. Since I can't leave a review, I'll leave a comment.

Some of these vectors don't seem to carry the right network version nor base fee:

```
"preconditions": {
		"variants": [{
			"id": "hyperdrive",
			"epoch": 86750,
			"nv": 4294967295
		}],
		"state_tree": {
			"root_cid": {
				"/": "bafy2bzaceajzl6zmeim6zkfz7zathwgjdqse7huwhqncjb2gb3ditkrdblot2"
			}
		},
		"basefee": 0,
		"circ_supply": 1000000000000000000000000000
	},
```

More questions:

1. Could you confirm that the circulating supply is correct?
2. Have you performed a round trip check against Lotus? (i.e. running these vectors against Lotus (or directly against specs-actors if you have a runner?)

**Comment by raulk** [comment]
Unfortunately these vectors don't work with the current Lotus runner, which is a deal-breaker for merging this PR. Example:

```
⟩ go run . exec --file ~/W/pl/test-vectors/corpus/specs_actors_v6/TestAggregateBadSender/8466b548087bb6c8c8469b4135521b147364ed7625467c8ac149f8785abcab5d-t0101-t0102-storageminer-26.json
# github.com/filecoin-project/lotus/cmd/tvx
ld: warning: could not create compact unwind for _blst_sha256_block_data_order: does not use RBP or RSP based frame
2022/01/04 14:34:11 executing test vector: TestAggregateBadSender
2022/01/04 14:34:11 ❌ exit code of msg 0 did not match; expected: 18, got: SysErrorIllegalActor(9)
2022/01/04 14:34:11 ❌ gas used of msg 0 did not match; expected: 464853, got: 195719
2022/01/04 14:34:11 ❌ test vector failed for variant hyperdrive
```

**Comment by ZenGround0** [comment]
Not sure exactly what's going on as some version of vectors and lotus runner was working back when I PRed this.  I'll take a look and try to sort out the issue.

**Comment by raulk** [comment]
The fixes pushed herein + https://github.com/filecoin-project/lotus/pull/7881 on Lotus side makes all these vectors pass against Lotus.

**Review by raulk — APPROVED** [review]

**Pull request merged**
