### PR TITLE
Use json serialization for selectors

### LINKED ISSUE #77: selectors as json
given existing json serialization having the extra level of selector serialization seems un-needed. lets encode it as a json map or array of strings

### PR DESCRIPTION
**Pull request by willscott**
fix #77

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
This will remove the ability to do any boolean logic. I had thought of the possibility to express AND/OR conditions going forward, e.g.

```
[
  "chaos_actor=true,puppet_actor=true",  chaos AND puppet actors both required, OR
  "something_else=true"
]
```

But honestly, I don't see a use case for that, so I'm OK merging this patch.

However, we need to:

- [ ] update the schema (I'll push a commit here)
- [ ] update https://github.com/filecoin-project/lotus/pull/3081.

**Comment by raulk** [comment]
Will merge to have a concrete master commit to upgrade the test driver to, on Lotus side.

**Review by raulk — APPROVED** [review]

**Comment by austinabell** [comment]
> This will remove the ability to do any boolean logic. I had thought of the possibility to express AND/OR conditions going forward, e.g.
> 
> ```
> [
>   "chaos_actor=true,puppet_actor=true",  chaos AND puppet actors both required, OR
>   "something_else=true"
> ]
> ```
> 
> But honestly, I don't see a use case for that, so I'm OK merging this patch.
> 
> However, we need to:
> 
> * [x]  update the schema (I'll push a commit here)
> * [ ]  update [filecoin-project/lotus#3081](https://github.com/filecoin-project/lotus/pull/3081).

I see, didn't think this was the plan as it was just a string and not an array currently. I don't see how this limits from doing this, you're able to build that logic into a json map (or can just change to an array of selectors all the same as you would under the assumption that each element acts as an OR).

**Comment by raulk** [comment]
@austinabell yeah, it's just more verbose 🙃 But yeah, totally doable as an array of objects.

**Pull request merged**
