### PR TITLE
fix state tree constructor invocation for API changes

### PR DESCRIPTION
**Pull request by Stebalien**
lotus PR: https://github.com/filecoin-project/lotus/pull/4197

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Review by raulk — APPROVED** [review]

**Comment by raulk** [comment]
Actually, this needs fixing. I'll push to it.

**Comment by raulk** [comment]
I ended up fixing in #166; will merge from master and fix the conflicts here.

**Review by raulk — CHANGES_REQUESTED** [review]
@Stebalien mind changing this to a draft PR? We can't merge this because it depends on a Lotus branch that hasn't landed on master.

**Comment by Stebalien** [comment]
So, we're in a bit of a pickle. If we merge to master _before_ we merge this, that commit on master will break after we merge this and delete the branch.

**Comment by raulk** [comment]
@Stebalien Ah, understood! I see that https://github.com/filecoin-project/lotus/pull/4197 is approved for merge. Would you mind:

1. merging lotus master into your lotus PR
2. updating the commit here?

Reason: I landed some changes this morning that test-vectors `master` now depends on.

I'll fix up this PR in parallel. Then we'll be good to merge, and you can merge https://github.com/filecoin-project/lotus/pull/4197 using a real merge so that the commit we point to is not lost.

Thanks!

**Comment by raulk** [comment]
Merged from master here. Compilation will fail until filecoin-project/lotus#4197 is updated from lotus master, and the dependency is updated here.

**Comment by Stebalien** [comment]
> merging lotus master into your lotus PR

It's based on next, have you forward ported your changes?

**Comment by Stebalien** [comment]
Ok, I think I've fixed everything up.

**Review by raulk — APPROVED** [review]

**Comment by raulk** [comment]
Thanks! ❤️

**Pull request merged**
